//TEST GENERATED BY LLM

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "myalloc.h"

// ANSI Color Codes for terminal output
#define COLOR_GREEN "\033[0;32m"
#define COLOR_RED   "\033[0;31m"
#define COLOR_RESET "\033[0m"

// Global counters for the test summary
int tests_run = 0;
int tests_passed = 0;

// Upgraded test helper
void run_test(const char *name, int condition) {
    tests_run++;
    if (condition) {
        printf("  [ %sPASS%s ] %s\n", COLOR_GREEN, COLOR_RESET, name);
        tests_passed++;
    } else {
        printf("  [ %sFAIL%s ] %s\n", COLOR_RED, COLOR_RESET, name);
    }
}

int main() {
    printf("\n==========================================\n");
    printf("       STARTING ALLOCATOR TEST SUITE      \n");
    printf("==========================================\n\n");


    // --- Group 1: Basic Malloc & Edge Cases (1-8) ---
    {
        void *p1 = mymalloc(51200);
        run_test("1. Basic 50KB Allocation", p1 != NULL);
        myfree(p1);
        run_test("2. Freeing 50KB block", 1);
        
        void *p2 = mymalloc(0);
        run_test("3. mymalloc(0) returns NULL", p2 == NULL);
        
        void *p3 = mymalloc(1);
        run_test("4. Malloc 1 byte (smallest allocation)", p3 != NULL);
        
        void *p4 = mymalloc(16);
        void *p5 = mymalloc(32);
        run_test("5. Multiple concurrent allocations", p4 != NULL && p5 != NULL);
        
        myfree(p3);
        run_test("6. Freeing 1-byte block", 1);
        myfree(p4);
        myfree(p5);
        run_test("7. Freeing multiple blocks", 1);
        
        void *p6 = mymalloc(SIZE_MAX - 100); 
        run_test("8. Malloc(SIZE_MAX) fails gracefully (Returns NULL)", p6 == NULL);
    }

    // --- Group 2: Alignment Verification (9-13) ---
    {
        void *a1 = mymalloc(1);
        void *a2 = mymalloc(7);
        void *a3 = mymalloc(16);
        void *a4 = mymalloc(31);
        
        run_test("9. Alignment check (1 byte alloc -> 16 byte aligned)", ((uintptr_t)a1 % 16) == 0);
        run_test("10. Alignment check (7 byte alloc -> 16 byte aligned)", ((uintptr_t)a2 % 16) == 0);
        run_test("11. Alignment check (16 byte alloc -> 16 byte aligned)", ((uintptr_t)a3 % 16) == 0);
        run_test("12. Alignment check (31 byte alloc -> 16 byte aligned)", ((uintptr_t)a4 % 16) == 0);
        
        myfree(a1); myfree(a2); myfree(a3); myfree(a4);
        run_test("13. Freed all alignment test blocks", 1);
    }

    // --- Group 3: Calloc Specifics (14-20) ---
    {
        char *c1 = mycalloc(10, 5); // 50 bytes
        run_test("14. Calloc basic allocation (10 * 5)", c1 != NULL);
        
        int is_zero = 1;
        for (int i = 0; i < 50; i++) if (c1[i] != 0) is_zero = 0;
        run_test("15. Calloc zero-initialization verified", is_zero);
        
        void *c2 = mycalloc(0, 10);
        run_test("16. Calloc(0, size) returns NULL", c2 == NULL);
        
        void *c3 = mycalloc(10, 0);
        run_test("17. Calloc(num, 0) returns NULL", c3 == NULL);
        
        void *c4 = mycalloc(SIZE_MAX, 2); 
        run_test("18. Calloc integer overflow protection triggers", c4 == NULL);
        
        myfree(c1);
        run_test("19. Freed Calloc memory", 1);
        
        char *c5 = mycalloc(100, 1);
        c5[99] = 'Z';
        run_test("20. Calloc memory is writable", c5[99] == 'Z');
        myfree(c5);
    }

    // --- Group 4: Realloc Edge Cases & Data Integrity (21-31) ---
    {
        void *r1 = myrealloc(NULL, 100);
        run_test("21. Realloc(NULL, size) acts as malloc", r1 != NULL);
        
        void *r2 = myrealloc(r1, 0);
        run_test("22. Realloc(ptr, 0) acts as free (returns NULL)", r2 == NULL);
        
        char *r3 = mymalloc(20);
        strcpy(r3, "ReallocTest");
        run_test("23. Setup data for realloc growth", strcmp(r3, "ReallocTest") == 0);
        
        r3 = myrealloc(r3, 100);
        run_test("24. Realloc Growth succeeded", r3 != NULL);
        run_test("25. Data preserved after Realloc Growth", strcmp(r3, "ReallocTest") == 0);
        
        r3 = myrealloc(r3, 10); // Shrinking
        run_test("26. Realloc Shrink succeeded", r3 != NULL);
        run_test("27. Data preserved after Realloc Shrink (truncated check)", strncmp(r3, "ReallocTes", 10) == 0);
        
        void *r4 = myrealloc(r3, 10);
        run_test("28. Realloc to same size", r4 != NULL);
        
        myfree(r4);
        run_test("29. Freed Realloc memory", 1);

        char *r5 = mymalloc(4000);
        memset(r5, 'A', 3999);
        r5[3999] = '\0';
        r5 = myrealloc(r5, 8000);
        run_test("30. Realloc crossing page boundaries", r5 != NULL);
        run_test("31. Data preserved across page boundaries", r5[0] == 'A' && r5[3998] == 'A');
        myfree(r5);
    }

    // --- Group 5: Block Splitting & Coalescing (32-40) ---
    {
        void *b1 = mymalloc(100);
        void *b2 = mymalloc(100);
        void *b3 = mymalloc(100);
        run_test("32. Allocated adjacent blocks (A, B, C)", b1 && b2 && b3);
        
        myfree(b1);
        myfree(b2);
        run_test("33. Forward Coalescing (Freed A then B)", 1);
        
        void *b4 = mymalloc(400);
        void *b5 = mymalloc(400);
        myfree(b5);
        myfree(b4);
        run_test("34. Reverse Coalescing (Freed B then A)", 1);
        
        void *m1 = mymalloc(200);
        void *m2 = mymalloc(200);
        void *m3 = mymalloc(200);
        myfree(m1);
        myfree(m3);
        myfree(m2); // Should merge left and right
        run_test("35. Middle Coalescing (Freed A, C, then B)", 1);
        
        void *s1 = mymalloc(1024);
        myfree(s1);
        void *s2 = mymalloc(16);
        run_test("36. Block splitting (Allocated 16 bytes from 1024 byte free block)", s2 != NULL);
        
        void *s3 = mymalloc(16);
        run_test("37. Secondary split (Allocated another 16 bytes)", s3 != NULL);
        
        myfree(s2);
        myfree(s3);
        myfree(b3);
        run_test("38. Cleaned up split blocks", 1);

        void *reuse1 = mymalloc(50);
        myfree(reuse1);
        void *reuse2 = mymalloc(50);
        run_test("39. Exact block reuse (No splitting needed)", reuse1 == reuse2); // Should theoretically reuse same address
        myfree(reuse2);
        run_test("40. Freed reused block", 1);
    }

    // --- Group 6: Large Allocations & Mmap behavior (41-44) ---
    {
        void *l1 = mymalloc(8192); // 2 pages
        run_test("41. Large allocation (> 1 page size)", l1 != NULL);
        
        void *l2 = mymalloc(16384); // 4 pages
        run_test("42. Very large allocation (> 3 page sizes)", l2 != NULL);
        
        myfree(l1);
        run_test("43. Freed 2-page block", 1);
        
        myfree(l2);
        run_test("44. Freed 4-page block", 1);
    }

    // --- Group 7: Stress Testing (45-50) ---
    {
        int stress_pass = 1;
        void *ptrs[100];
        for(int i = 0; i < 100; i++) {
            ptrs[i] = mymalloc((i % 128) + 1); // 1 to 128 bytes
            if (!ptrs[i]) stress_pass = 0;
        }
        run_test("45. Stress: 100 sequential allocations", stress_pass);
        
        stress_pass = 1;
        for(int i = 0; i < 100; i += 2) {
            myfree(ptrs[i]); // Free evens
        }
        run_test("46. Stress: Fragmented freeing (freed all even blocks)", 1);
        
        stress_pass = 1;
        for(int i = 0; i < 100; i += 2) {
            ptrs[i] = mymalloc((i % 64) + 1); // Reallocate into holes
            if (!ptrs[i]) stress_pass = 0;
        }
        run_test("47. Stress: Fragmented allocation (filled holes)", stress_pass);
        
        for(int i = 0; i < 100; i++) {
            myfree(ptrs[i]); // Clean up all
        }
        run_test("48. Stress: Cleaned up 100 fragmented blocks", 1);
        
        stress_pass = 1;
        void *cycle_ptr = NULL;
        for(int i = 0; i < 1000; i++) {
            cycle_ptr = mymalloc(64);
            if (!cycle_ptr) stress_pass = 0;
            myfree(cycle_ptr);
        }
        run_test("49. Stress: 1000 rapid Malloc/Free cycles on same pointer", stress_pass);

        void *alternating1 = mymalloc(16);
        void *alternating2 = mymalloc(10240);
        void *alternating3 = mymalloc(32);
        run_test("50. Stress: Alternating tiny/huge allocations", alternating1 && alternating2 && alternating3);
        myfree(alternating1); myfree(alternating2); myfree(alternating3);
    }

    // Test 1 & 2: Basic Allocation and Free
    void *p1 = mymalloc(51200); // 50kb
    run_test("Basic Allocation (50KB)", p1 != NULL);
    myfree(p1);
    run_test("Freeing large block", 1); 

    // Test 3: Multiple Allocations & Alignment
    void *p2 = mymalloc(100);
    void *p3 = mymalloc(200);
    void *p4 = mymalloc(300);
    run_test("Multiple consecutive allocations", (p2 != NULL && p3 != NULL && p4 != NULL));
    
    // Test 4: Data Integrity (Crucial Test!)
    // If your block splitting logic is off, writing to p2 might corrupt p3.
    strcpy((char*)p2, "Hello Allocator!");
    run_test("Data Integrity (Writing & Reading memory)", strcmp((char*)p2, "Hello Allocator!") == 0);

    // Test 5: Realloc Growth
    p2 = myrealloc(p2, 150);
    // It should successfully resize AND preserve the data we just wrote.
    run_test("Realloc Growth (Data Preserved)", p2 != NULL && strcmp((char*)p2, "Hello Allocator!") == 0);

    // Test 6: Calloc Zero Initialization
    char *p_calloc = mycalloc(10, 5); // 50 bytes total
    int is_zero = 1;
    if (p_calloc) {
        for (int i = 0; i < 50; i++) {
            if (p_calloc[i] != 0) is_zero = 0; // Check if every byte is exactly 0
        }
    }
    run_test("Calloc (Zero Initialization)", p_calloc != NULL && is_zero);

    // Test 7: Coalescing Logic Simulation
    // Freeing p2 and p3 should merge them into a single block of roughly 350+ bytes.
    myfree(p2);
    myfree(p3);
    
    // If coalescing works, a new allocation of 250 bytes should easily fit in that newly merged space.
    void *p5 = mymalloc(250); 
    run_test("Coalescing & Block Split (Merging p2 and p3)", p5 != NULL);

    // Final Cleanup
    myfree(p4);
    myfree(p_calloc);
    myfree(p5);

    printf("\n==========================================\n");
    if (tests_passed == tests_run) {
        printf(" RESULTS: %s%d / %d Tests Passed%s\n", COLOR_GREEN, tests_passed, tests_run, COLOR_RESET);
    } else {
        printf(" RESULTS: %s%d / %d Tests Passed%s\n", COLOR_RED, tests_passed, tests_run, COLOR_RESET);
    }
    printf("==========================================\n\n");

    // Only uncomment this if a test fails and you need to debug the final state
    // printf("Final Heap State:\n");
    // print_heap();

    return 0;
}